ATPAY_HOST: 'http://'
ATPAY_USERNAME: 'yourusername'
ATPAY_PASSWORD: 'yourpassword'
ATPAY_VALID_CARD_AVS: '111'
ATPAY_VALID_CARD_EXPIRE_DATE: '0199'
ATPAY_VALID_CARD_NAME_ON_CARD: 'test delete'
ATPAY_VALID_CARD_NUMBER: '1111111111111111'
ATPAY_TEST_ACCOUNT_ID: '111'
ATPAY_TEST_SUB_ACCOUNT_ID: '1'
